// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200703.9

#ifndef WINRT_Calculator_1_H
#define WINRT_Calculator_1_H
#include "winrt/impl/Calculator.0.h"
WINRT_EXPORT namespace winrt::Calculator
{
    struct __declspec(empty_bases) ICalculatorState :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICalculatorState>
    {
        ICalculatorState(std::nullptr_t = nullptr) noexcept {}
        ICalculatorState(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
