// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200703.9

#ifndef WINRT_Calculator_2_H
#define WINRT_Calculator_2_H
#include "winrt/impl/Calculator.1.h"
WINRT_EXPORT namespace winrt::Calculator
{
    struct __declspec(empty_bases) CalculatorState : Calculator::ICalculatorState
    {
        CalculatorState(std::nullptr_t) noexcept {}
        CalculatorState(void* ptr, take_ownership_from_abi_t) noexcept : Calculator::ICalculatorState(ptr, take_ownership_from_abi) {}
        CalculatorState();
    };
}
#endif
