namespace CalculatorInterface
{
    [default_interface]
    runtimeclass Expression
    {
        Expression();
        Boolean ParseChar(Char c);
        void Clear();
        String FinalizeSimplifyPrint();
    }
}
