import "Expression.idl";

namespace CalculatorInterface
{
    [default_interface]
    runtimeclass Parser
    {
        Parser();
        Boolean ParseChar(Char c);
        void Finalize();
        //Expression GetResult();
    }
}
